x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
x-common-env: &common-env
  PGID: 1000
  PUID: 1000
  TZ: Europe/Paris

networks:
  public:
    external: true

services:
  sablier:
    cap_drop:
      - "ALL"
    command:
      - start
      - --provider.name=docker_swarm
      - --sessions.default-duration=1m
      - --strategy.dynamic.default-theme=ghost
      - --strategy.dynamic.show-details-by-default=false
      - --logging.level=debug
    deploy:
      !!merge <<: *common-deploy
    environment:
      !!merge <<: *common-env
    image: sablierapp/sablier:1.16.1@sha256:4137043766568f4254d30e6c970918bdb522a2213af8ddee4a379f95673510b6
    networks:
      - public
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock